index_col: 'flat_id'
target_col: 'price'
n_splits: 3
metrics: ['rmse', 'mae', 'r2']

n_jobs: 1

model_params:
  n_estimators: 150
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 'sqrt'
  max_depth: 20
  random_state: 42
